### ISSUE TITLE
wotmods and removed mods

### ISSUE THREAD

**Issue by elektrosmoker** [Willster419/RelhaxModpackDatabase#53]
there are several mods that were converted to wotmods!
this is not ok!
i want them to get reverted!!

also there were several mods removed because of dead devurls - do you have tested the mod itself? is it working or is it not working?
why remove mods that work??

only because a developer is using wotmods for everything doesnt mean we have to use it either!
extract the files from the wotmods and use the mod as it was before!!

thank you!

**Comment by Willster419** [comment]
I edited your post to clean up the language and fix typeos.

We had a conversation this morning about what happened yesterday, and as per our discussion, I am sharing the results here. We discussed two things:

1. Removing `TankSkinsMisc_ColoredPenetration_webium`. Commits relevant on this topic:
https://github.com/Willster419/RelhaxModpackDatabase/commit/1b086b420cb37166a91b1b80a89e07bc45f8ec04
https://github.com/Willster419/RelhaxModpackDatabase/commit/2cacc646a7673731bc6b3943f28366161fa44f52
https://github.com/Willster419/RelhaxModpackDatabase/commit/ae82e6fbd11a0d4ee41e9e95c8dfdd71704d77f7
https://github.com/Willster419/RelhaxModpackDatabase/commit/4e03b4a6f2f88af5cba95d3e4d6f1620cc0decf6

The reason that illusion wanted to, and I authorized removal was because the dev url link was old and no longer works. There was no other information on the mod, so at the time late last night (for me) all i had to go on was what he told me. I made the decision at the time that we should remove it.

From our discussion, there are two view points about mods like this:
1. "The developer no longer supports it, it's very old, why should be keep it?"
2. "In mods like this, it's just a dds file, and it's not *technically* broken, so why remove it?"

This is when it was found that back in late 2018 or early 2019, you (elektro) and updated that mod to make it compatible. It's a very small mod, and in reality it's just damage sticker dds files. With this information, I would not have authorized the removal.

The follow-up action is that you said you can remove the dev url, and either a) add yourself as a maintainer and/or b) update the internal notes about the history of this mod.

Additionally, we discussed a system to use in the future to prevent this kind of situation from happening - a "deprecated" tag. See issue (TODO)

**Comment by Willster419** [comment]
Second discussion:
2. The changing of flagsLib (but doesn't need to be specifically this mod) from original res_mods to wotmods.
Commits relevant on this topic:
https://github.com/Willster419/RelhaxModpackDatabase/commit/30a8e7c04fb3c488be1e194684acbc7e354833c3
https://github.com/Willster419/RelhaxModpackDatabase/commit/d7deba34cd833ddf645f98eac50b64d4f738da1b
https://github.com/Willster419/RelhaxModpackDatabase/commit/81ef3b57d18c444ebc626fe996ffbb61eb0e3b92
https://github.com/Willster419/RelhaxModpackDatabase/commit/60658a40308b1932b7273f474d6b300875c53aad
https://github.com/Willster419/RelhaxModpackDatabase/commit/5997685496bfc748366e64de0f4466c0f446233c

This also was discussed in slack. Illusion originally made the initial change to update them *and* move them to using wotmods. However, we talked in slack that while it does take more time to remove them and put into res_mods, you mentioned that there was a legacy reason as to why it needed to be done, possibly because of file override order conflicts.

After back an forth, I stepped in and gave the following ~decree~ action:
"Experimenting and optimizing how we package our mods is great, but please leave that to after patch days. Just update mods during patch days, because we know that system should work. If it doesn't, that's a different discussion."

Illusion agreed and reverted his work. However, after discussion between us, we found that the older files he reverted to were accidentally still in wotmod format. This looks like an honest mistake, especially because he removed the dependencies to load order. So then you reverted the zip files back further to old ones that are still res_mods. They still need to be updated, but everything has been explained and is resolved.

**Comment by Arkhorse** [comment]
Wotmods are what every mod will eventually be. They are also the way most authors are deploying their mods. There is the load_order.xml file to resolve conflicts, without us needing to do 5 minutes of work per mod. Anyways, the changes I made to FlagsLib got reverted, and put on another branch, to be used after patch day.

**Comment by elektrosmoker** [comment]
my arguments against changing mods to wotmod:
- when we will automate everything, the crc of the files INSIDE the wotmod got checked. this means this files get extracted in all situations. 
it should be no problem (and faster for the amount of mods we have) to move this into the res_mods folder than repacking it to a wotmod again. -> this doesnt mean generally that we should not  have wotmods - but this makes it . 

- i personally do not like wotmods because when doing the updates manually, you always need to open the wotmod inside the archive to check if the files are updated or not (date and crc of wotmods is irrelevant [see hawg´s mods]).
yes, once a mod´s infofields in the database are filled out correctly you will notice what files it are used/inside and how to treat this mod and if automated the xml will do everything.
BUT if you search for any errors that may happened while packing or updating or writing the xml - you will also need more time to check the double-packed files for the corrupted files inside.

a load_order.xml is fine that prevents files from  getting overwritten or the game to crash because of conflicting files.
-> my suggestion: use load_order only for images and not for scripts!

and another point:
if there are mods in a section that are using mods/res_mods - please use the same folder for new added zipfiles (this would be only a one time work. automation...)
this i think should be done for all mod -> use the same template for adding as existing mods use.


my 2 cents...
if my english was to broken to understand, tell me ;)

**Comment by 123Gauss** [comment]
@Willster & @Arkhorse: see question in slack
@elektrosmoker: thx read ur mesage

**Comment by Arkhorse** [comment]
## Ok, let me attempt to tell you why `wotmods` are what we should be using:

1. WG, at some point in the future, will be removing the `res_mods` folder. This means all mods will be in `wotmod` format. No, we have not control over that, nor do we know when this will happen. If they did that today, sound mods would be broken. 
2. `load_order.xml` only works on "Same file name", not same content. It was primarily introduced to the modpack to make the custom tank skins and tank skin categories work better. However, it can be used for any category.
3. With automation, CRC's will not be checked. Instead md5 hashes will be. Im pretty sure its very easy to get the md5 hash for the `res` folder inside the `wotmod` with that tool.

## Now, let me address your reasons:

Reason 1 and 2 are the same. You worry about whether or not a mod has an actual update or not. For me, I have stopped this practice. Why? Because it takes too much time. For me, if the initial file has a different CRC, whether that is a wotmod, or the res_mods folder, it doesnt matter. If they are different, I update. No looking inside for what file got changed, no looking inside of the wotmod for additional crc's. Its faster this way. Less work. And thats what we need. We take the longest to update on patch day. We need to be cutting things out of our update process, that are not fully needed. 

As for categories using one mod type or the other, the mods folder should win 99% of the time. The only category that MUST be entirely `res_mods` is the sounds category. The reason for this is written above. When WG removes the `res_mods` folder, we dont want a database where every single mod is using res_mods for no good reason (good reasons exist, I know). That would require alot of work on our end to change everything over. Remember, `wotmods` are being increasingly used. If we stay with using our current method, our work load will only increase over time. Not something we want.

## As for file conflict resolution:

The `load_order.xml` is the single best way to do it. Its akin to the `loadorder.txt` in the fallout games. The lowest one in the order will always win. No way for that to ever break. 

So, I hope this helps you understand what I am attempting to do.
